version: "3.8"
services:
  api:
    build: ./api
    container_name: api_c
    ports:
      - "4000:4000"
    volumes:
      - ./api:/app
      - api_node_modules:/app/node_modules

  client:
    build: ./svelte-app
    container_name: svelte_c
    ports:
      - "3002:3002"
    volumes:
      - ./svelte-app:/app
      - svelte_node_modules:/app/node_modules

volumes:
  api_node_modules:
  svelte_node_modules:
